### ISSUE TITLE
Miniloader research gives an item that cannot be crafted

### ISSUE THREAD

**Issue by TheNEStOnline** [Project-Corona/Project-Corona#1]
Hi thanks for a nice mod pack :)

I found that when I research Miniloader then it gives me 2 new items that cannot be crafted.
I think it's a clash between deadlock-beltbox-loaders_2.3.4 and miniloader_1.10.8 mods.

I have the FNEI mod and cannot find the recipe there either.

![2020-04-19 21_34_48-Greenshot](https://user-images.githubusercontent.com/26241410/79697939-da1fcd80-8285-11ea-80d4-f6667fbdf8b3.png)
![2020-04-19 21_37_35-Greenshot](https://user-images.githubusercontent.com/26241410/79697978-17845b00-8286-11ea-94a6-b15c521c493b.png)

**Comment by JDOGG88** [comment]
Interesting, miniloader is supposed to be overwritten by the deadlock graphics and the recipes are supposed to be updated by the mod pack.  I will look into it today and see if I can't figure out what's going on.  Thank you for the find :D

**Comment by JDOGG88** [comment]
Could you do me a favor and send me your save file and mod-list.json file please?

**Comment by JDOGG88** [comment]
Actually I think I know what's causing the issue, update your miniloader mod to the latest version.  The author of that mod changed how he called out his entities and it's not being overwritten properly I think.  I'll have to update dependencies list to make the mod pack use the latest version of miniloader.

**Comment by TheNEStOnline** [comment]
Now the mods and Procject Corona is up to date but still it shows the none crafetable loader.
Ps. I am running a dedicated server on steamCMD but that should not change the recipes
![2020-04-21 08_19_02-Greenshot](https://user-images.githubusercontent.com/26241410/79832221-41826e00-83a9-11ea-983b-d0814b2d10a4.png)

**Comment by JDOGG88** [comment]
No, It shouldn't.  I've been working on overhauling the recipe's file which I believe will fix the issue.  I should be able to push it to the mod portal soon.

**Comment by JDOGG88** [comment]
This should now be fixed, let me know if you have any other issues.

**Comment by TheNEStOnline** [comment]
Now I get this error starting Factorio.

![2020-04-21 18_57_19-Greenshot](https://user-images.githubusercontent.com/26241410/79891969-0a8c7680-8402-11ea-9a86-782e80c2ce78.png)

**Comment by JDOGG88** [comment]
Would you know how to edit it by chance and if so can you go to that line and change ipairs -> pairs if not i can change it and push it to github for you to download from here to test it.  I don't get that error and I'm wondering if it's because you already started the play through.  If that's the case I will need to troubleshoot your save and try to create a fix.

**Comment by JDOGG88** [comment]
That should be fixed now, I forgot to call it out to only be used if the beltlayer mod is used.  Which if you weren't using beltlayer then that error would pop up.
