### ISSUE TITLE
crash @ opening

### ISSUE THREAD

**Issue by sikef** [Project-Corona/Project-Corona#2]
game version 0.18.25 ( steam )

![error](https://user-images.githubusercontent.com/65654847/82440246-d7e7a380-9abd-11ea-9441-9eeeaae83842.jpg)
![mods](https://user-images.githubusercontent.com/65654847/82440253-d918d080-9abd-11ea-877a-0d5ccb1249aa.jpg)

**Comment by JDOGG88** [comment]
Can you also show me your mod settings too please?

**Comment by sikef** [comment]
![1](https://user-images.githubusercontent.com/65654847/82516047-a1506e00-9b3b-11ea-85d3-2a477fc3a08a.jpg)
![2](https://user-images.githubusercontent.com/65654847/82516053-a7464f00-9b3b-11ea-8667-c6815b783ba1.jpg)
![3](https://user-images.githubusercontent.com/65654847/82516056-aa413f80-9b3b-11ea-8da3-88f20a6447fd.jpg)
![4](https://user-images.githubusercontent.com/65654847/82516060-aca39980-9b3b-11ea-99bc-4b23491c23dc.jpg)
![5](https://user-images.githubusercontent.com/65654847/82516064-af05f380-9b3b-11ea-921a-d7a6ecb1f4a4.jpg)
![map](https://user-images.githubusercontent.com/65654847/82516328-423f2900-9b3c-11ea-9c9f-5bae463c6091.jpg)
![player](https://user-images.githubusercontent.com/65654847/82516338-466b4680-9b3c-11ea-9735-7cd8b21be2d0.jpg)

**Comment by sikef** [comment]
fresh install, last version of game ( deleted old one )

**Comment by JDOGG88** [comment]
[project-corona_0.18.8.zip](https://github.com/Project-Corona/Project-Corona/files/4660456/project-corona_0.18.8.zip)

I pushed an update to github which you can download or use the link above.  There are still things I need/want to do before I push the actual update to the mod portal.  Please let me know if this resolves your issue or not or creates other problems (this was kind of a quick fix) so I'm not sure if I added some other thing in to go wrong.

**Comment by sikef** [comment]
it works, tnx :)

**Comment by sikef** [comment]
Little feed back. 
Small electric poles are hard to make early game. 
Poles need wood
Wood -> greenhouse
greenhouse -> glass
Glass -> quartz 
For Quartz -> electric omnitractor 1
EO -> too many researches. 

Tnx again

**Comment by JDOGG88** [comment]
That's actually a bug you found for me haha thanks.  The glass is supposed to be replaced with copper. The line that's supposed to make that happen is incorrect.  I will fix that for the next update.

FYI the update will be version 0.18.8 so I'll leave this issue open to inform you so you can redownload it from the mod portal.  Thanks for the feedback :D

**Comment by JDOGG88** [comment]
[project-corona_0.18.8.zip](https://github.com/Project-Corona/Project-Corona/files/4665098/project-corona_0.18.8.zip)

here's a quick fix for the greenhouse recipe

**Comment by sikef** [comment]
new update for game ( steam auto updated :/ )
game version 0.18.26 ( steam ) 
mod updated too ( from link u sent )

Edit 1: i roll back game to 18.25 same error.
Edit 2: i roll back mod 18.8 ( no glass fix ) it works

![error](https://user-images.githubusercontent.com/65654847/82630848-bf8a9c80-9c15-11ea-84e1-916c47fdccb5.jpg)

**Comment by sikef** [comment]
and one more thing, 
how about make easy ore processing?
too many researches for ore processing, my played time almost  6 hours.
1 hour i spent for glass
2 hour for ore processing to get enough ore for red and green science.
i don't have a green chip belt. just 1 iron 1 copper belt.

**Comment by JDOGG88** [comment]
[project-corona_0.18.8.zip](https://github.com/Project-Corona/Project-Corona/files/4669058/project-corona_0.18.8.zip)

Sorry, this link will update the recipe properly.  

As for the ore processing this is handled by omnimatter,  it gets more efficient with the more research you do.  There is a startup setting for omnimatter called "Beginner help" that you can change to make the techs cheaper to get to electric omnitractors.  There are also other setting to reduce the amount of techs in between tiers of omnitractors that can be changed.

**Comment by JDOGG88** [comment]
I have pushed the official 0.18.8 update to the mod portal so please re-download :D
